---
- name: Show IP addresses of the target machine
  hosts: lb1
  tasks:
    - name: Run 'ip addr' command
      command: ip addr
      register: ip_output

    - name: Display IP addresses
      debug:
        var: ip_output.stdout_lines

- name: Install Keepalived and Configure
  hosts: lb1
  become: yes
  tasks:
    - name: Check if Keepalived is installed
      command: dpkg -l keepalived
      register: keepalived_check
      ignore_errors: true

    - name: Install Keepalived if not installed
      apt:
        name: keepalived
        state: present
        update_cache: yes
      when: keepalived_check.rc != 0

    - name: Create /etc/keepalived/keepalived.conf file
      blockinfile:
        path: /etc/keepalived/keepalived.conf
        block: |
          vrrp_script chk_haproxy {
              script "killall -0 haproxy"
              interval 2
              weight 2
          }

          vrrp_instance VI_1 {
              interface ens33
              state BACKUP
              priority 100
              virtual_router_id 51
              virtual_ipaddress {
                  192.168.1.19
              }
              track_script {
                  chk_haproxy
              }
          }
      when: ansible_distribution == 'Ubuntu'  # Adjust this condition based on your OS

- name: Install Docker if not installed
  hosts: lb1
  tasks:
    - name: Check if Docker is installed
      command: dpkg -l docker.io
      register: docker_check
      ignore_errors: yes

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0

- name: Install Docker
  hosts: lb1
  become: yes
  become_user: root
  tasks:
    - name: Install Docker
      apt:
        name: docker
        update_cache: yes
        state: present

- name: Create users
  hosts: lb1
  become: yes
  tasks:
    - name: Create user
      user:
        name: amine
        state: present
        createhome: yes
    - debug:
        msg: "{{ shell_result.stdout_lines }}"

