---
- hosts: swarm-master-1
  become: true

  tasks:
    - name: Initialize the cluster
      shell: docker swarm init --advertise-addr 192.168.56.10 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
        
    - name: copy Docker Compose files
      copy: src=files/docker-compose.yml dest=/tmp/

    - name: Go to the folder and execute command
      shell: cd /tmp/ && docker stack deploy -c docker-compose.yml wp

    - name: Test docker compose
      docker_compose:
        project_src: /tmp/
        state: present
      register: __docker_compose

    - name: Output
      debug:
        var: __docker_compose
      
