---
- hosts: swarm-master-1
  become: true

  tasks:
    - name: Initialize the cluster
      shell: docker swarm init --advertise-addr 192.168.56.10 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
        
    - name: copy Docker Compose files
      copy: src=files/docker-compose.yml dest=/tmp/
#       src: files/{{ item }}
#       dest: /swarm-vagrant-ansible/Ansible/{{ item }}
#     loop:
#     - docker-compose.yml
   

   # use files parameter to use multiple docker-compose.yml files
#   - name: deploy Docker Compose stack
#     community.docker.docker_compose:
#       project_src: /swarm-vagrant-ansible/Ansible
#       files:
#       - docker-compose.yml
   

#    - name: " Copy files directory"
#      copy:
#      src: files/docker-compose.yml
#      dest: /tmp/

    - name: Test docker compose
      docker_compose:
        project_src: /tmp/
        state: present
      register: __docker_compose

    - name: Output
      debug:
        var: __docker_compose
      
